### ISSUE TITLE
Lacking lib.rs for unit testing.

### ISSUE THREAD

**Issue by Plommonsorbet** [BenSchZA/pier#13]
Most of the code in main.rs should probably be moved into lib.rs so it's possible to create unit tests for the code.

I could start working on this next time I get a chance to sit down and do some coding.

**Comment by BenSchZA** [comment]
Happy for you to get started on this.

**Comment by Plommonsorbet** [comment]
Basic testing has been added and the main code has been moved to lib.rs in the latest pull request. Closing this issue.
