### ISSUE TITLE
Run output boiler plate suggestions?

### ISSUE THREAD

**Issue by Plommonsorbet** [BenSchZA/pier#28]
Currently it's a bit hard to pipe the output of pier into anything else as there is a bit of boiler plate in the run output. I've been thinking a bit about how to solve this, some of my ideas are:
- Remove it completely. 
- Move it to only print on verbose mode. 
- Add an option for a 'quiet-mode'

Personally I think the best option would be to move it to only print in verbose mode, I think it can be nice to see sometimes. But usually you want to be able to do something with the output and having to use a flag every time you want to pipe pier to something else could get a bit annoying.

I'd love to hear your opinion Ben / anyone else :)

**Comment by BenSchZA** [comment]
@Plommonsorbet I agree, initially it was there to debug the output, but now it makes sense to only do that in a verbose mode which can be expanded in future. 100% agree re. being able to pipe the output.

**Comment by Plommonsorbet** [comment]
Made a pull request to implement this. #33

**Comment by Plommonsorbet** [comment]
This change has now been merged.
